name: Docker

on:
  push:
    branches:
      - master

env:
  IMAGE_NAME: "valentineus/meteor"

jobs:
  push:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        include:
          version: ["1.10", "1.6"]

    steps:
      - uses: docker/build-push-action@v1
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
          tag: ${{ matrix.include.version }}
          repository: valentineus/meteor
          dockerfile: "default/release/Dockerfile"
          buildargs: "RELEASE=${{ matrix.include.version }}"