name: Docker

on:
  push:
    branches:
      - master

jobs:
  push-latest:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
        with:
          ref: ${{ github.event.pull_request.head.ref }}
          fetch-depth: 0

      - uses: docker/build-push-action@v1
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
          repository: valentineus/meteor
          path: latest
          tag_with_ref: true
          tag_with_sha: true

  push-release:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        version:
          - "1.9"
          - "1.8"
          - "1.7"
          - "1.6"
          - "1.5"
          - "1.4"

    steps:
      - uses: actions/checkout@v2
        with:
          ref: ${{ github.event.pull_request.head.ref }}
          fetch-depth: 0

      - uses: docker/build-push-action@v1
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
          repository: valentineus/meteor
          tags: ${{ matrix.version }}
          path: release
          build_args: RELEASE=${{ matrix.version }}
          tag_with_ref: true
          tag_with_sha: true