name: Docker

on:
  push:
    branches:
      - master

env:
  IMAGE_NAME: "valentineus/meteor"

jobs:
  push-latest:
    runs-on: ubuntu-latest

    steps:
      - uses: docker/build-push-action@v1
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
          repository: valentineus/meteor
          path: "release"
          tag_with_ref: true
          tag_with_sha: true

  push-release:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        version:
          - "1.10"
          - "1.6"

    steps:
      - uses: docker/build-push-action@v1
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
          tag: ${{ matrix.version }}
          repository: valentineus/meteor
          path: "latest"
          buildargs: "RELEASE=${{ matrix.version }}"
          tag_with_ref: true
          tag_with_sha: true